version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sibeisecret
  web:
    build: .
    command: bundle exec rails s
    image: dockertest
    volumes:
      - .:/app # This mounts the current directory into the /app folder of the web container so you can still edit it and watch the live changes play out
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:sibeisecret@db/dockertest_development